apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-efs
provisioner: snehal-lw

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: efs-wordpress
   annotations:
       volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
       - ReadWriteMany
  resources:
      requests:
          storage: 20Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
   name: efs-mysql
   annotations:
         volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
     requests:
         storage: 20Gi
