apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRolebinding
metadata: 
  name : nfs-provisioner-role-binding
subjects:
   - kind: SeviceAccount
     name: default
     namespace: default
roleRef: 
     kind: ClusterRole
     name: Cluster-admin
     apiGroup: rbac.authorization.k8s.io  